name: Navidrome
version: 1.0_0.54.4
slug: navidrome
description: Modern Music Server and Streamer compatible with Subsonic/Airsonic
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
url: https://github.com/celynw/ha-addons/tree/main/navidrome
webui: http://[HOST]:[PORT:4533]
ports:
  4533/tcp: 4533
ports_description:
  4533/tcp: Web UI
devices:
  - /dev/dri
  - /dev/dri/card0
  - /dev/dri/card1
  - /dev/dri/renderD128
  - /dev/vchiq
  - /dev/video10
  - /dev/video11
  - /dev/video12
  - /dev/video13
  - /dev/video14
  - /dev/video15
  - /dev/video16
  - /dev/ttyUSB0
  - /dev/sda
  - /dev/sdb
  - /dev/sdc
  - /dev/sdd
  - /dev/sde
  - /dev/sdf
  - /dev/sdg
  - /dev/nvme
  - /dev/nvme0n1p1
  - /dev/nvme0n1p2
  - /dev/mmcblk
  - /dev/fuse
  - /dev/sda1
  - /dev/sdb1
  - /dev/sdc1
  - /dev/sdd1
  - /dev/sde1
  - /dev/sdf1
  - /dev/sdg1
  - /dev/sda2
  - /dev/sdb2
  - /dev/sdc2
  - /dev/sdd2
  - /dev/sde2
  - /dev/sdf2
  - /dev/sdg2
  - /dev/sda3
  - /dev/sdb3
  - /dev/sda4
  - /dev/sdb4
  - /dev/sda5
  - /dev/sda6
  - /dev/sda7
  - /dev/sda8
  - /dev/nvme0
  - /dev/nvme1
  - /dev/nvme2
map:
  - media:rw
  - share:rw
options:
  ND_MUSICFOLDER: null
  ND_DATAFOLDER: /config/addons_config/navidrome
  ND_ENABLESTARRATING: true
  ND_ENABLEFAVOURITES: true
  ND_LISTENBRAINZ_ENABLED: true
  ND_ENABLESHARING: false
  ND_SHAREURL: ""
  ND_ENABLEGRAVATAR: false
  ND_SPOTIFY_ID: ""
  ND_SPOTIFY_SECRET: ""
  ND_LASTFM_ENABLED: false
  ND_LASTFM_APIKEY: ""
  ND_LASTFM_SECRET: ""
  ND_JUKEBOX_ENABLED: false
  ND_JUKEBOX_DEFAULT: ""
  ND_JUKEBOX_DEVICES: ""
  ND_TRANSCODINGCACHESIZE: "100MB"
  ND_SCANSCHEDULE: "@every 24h"
  ND_SESSIONTIMEOUT: "30m"
  ND_UIWELCOMEMESSAGE: ""
  ND_UILOGINBACKGROUNDURL: ""
  ND_DEFAULTPLAYLISTPUBLICVISIBILITY: false
  ND_SMARTPLAYLISTREFRESHDELAY: "5s"
  PUID: 0
  PGID: 0
  ND_LOGLEVEL: "info"
  ND_ENABLEINSIGHTSCOLLECTOR: true
schema:
  ND_MUSICFOLDER: str
  ND_DATAFOLDER: str
  ND_ENABLESTARRATING: bool
  ND_ENABLEFAVOURITES: bool
  ND_LISTENBRAINZ_ENABLED: bool
  ND_ENABLESHARING: bool
  ND_SHAREURL: str?
  ND_ENABLEGRAVATAR: bool
  ND_SPOTIFY_ID: str?
  ND_SPOTIFY_SECRET: password?
  ND_LASTFM_ENABLED: bool
  ND_LASTFM_APIKEY: password?
  ND_LASTFM_SECRET: password?
  ND_JUKEBOX_ENABLED: bool
  ND_JUKEBOX_DEFAULT: str?
  ND_JUKEBOX_DEVICES: str?
  ND_TRANSCODINGCACHESIZE: str
  ND_SCANSCHEDULE: str
  ND_SESSIONTIMEOUT: str
  ND_UIWELCOMEMESSAGE: str?
  ND_UILOGINBACKGROUNDURL: str?
  ND_DEFAULTPLAYLISTPUBLICVISIBILITY: bool
  ND_SMARTPLAYLISTREFRESHDELAY: str
  PUID: int
  PGID: int
  ND_LOGLEVEL: list(error|warn|info|debug|trace)
  ND_ENABLEINSIGHTSCOLLECTOR: bool
ingress: true
ingress_entry: app
ingress_port: 4533
panel_icon: mdi:record-circle-outline
init: false
